Feats: Add requirments.txt
UBC-MDS/datasci_salaries_py pull request #32
Opened 2022-03-01 23:51 UTC by PANDASANG1231

2022-03-01 23:53 UTC, joshsia requested changes
@PANDASANG1231 Could you add `gunicorn`?

2022-03-02 00:18 UTC, artanzand approved these changes
Well done!

2022-03-02 00:45 UTC, joshsia commented on requirements.txt
> +jsonschema==3.2.0
```suggestion
jsonschema==3.2.0 
gunicorn
```

2022-03-02 00:46 UTC, joshsia approved these changes

2022-03-02 00:46 UTC, merged